"use strict";

const diff = require('deep-diff').diff;
const fs = require('fs');

const validationLibrary = function() {};

/**
 * Generates an Error message string by parsing a given differences object collection generated by comparing two JSON objects
 * using the diff method from the 'deep-diff' node module.
 * @param  {Array} diffObjectsCollection - An array containing difference objects. Object schema can be found online
 * on the documentation for the 'deep-diff' node module.
 * @return {string} A string that details each difference found when comparing two JSON objects.
 */
validationLibrary.generateDifferencesError = function(diffObjectsCollection) {
    let errorMessage = "";
    
    diffObjectsCollection.forEach(function(diffObject) {
        if (diffObject.kind == 'A' && diffObject.path === undefined) {
            errorMessage += "Missing item in array \n" +
                "Path:      Root level\n" +
                "Index:    " + diffObject.index + "\n" +
                "Expected: " + diffObject.item.lhs + "\n" +
                "Actual:   " + diffObject.item.rhs + "\n\n"
        }

        else if (diffObject.kind == 'A') {
            errorMessage += "Missing item in array \n" +
                "Path:    " + diffObject.path + "\n" +
                "Index:   " + diffObject.index + "\n" +
                "Item:    " + diffObject.item.rhs + "\n\n"
        }
        
        else if (diffObject.kind == 'E') {
            errorMessage += "Values don't match\n" +
                "Path:      " + diffObject.path + "\n" +
                "Expected:  " + diffObject.lhs + "\n" +
                "Actual:    " + diffObject.rhs + "\n\n"
        }
        
    });
    
    return errorMessage;
};

/**
 * Compares two JSON objects and throws an error if any differences are found between the objects. Calls the 
 * generateDifferencesError method to generate a string to be used when throwing an error.
 * @param  {object} actual - A JSON object
 * @param  {object} expected - A JSON object
 * @param  {Array} ignoredKeys - A list of keys to be ignored during the comparison of the JSON objects
 */
validationLibrary.validateObjectsAreEqual = function(actual, expected, ignoredKeys) {
    if (ignoredKeys === undefined) {
        ignoredKeys = [];
    }
    
    let differences = diff(actual, expected, function(path, key) {
        return ignoredKeys.indexOf(key) >= 0;
    });
    
    if (differences != undefined) {
        let errorMessage = this.generateDifferencesError(differences);
        throw new Error("The following differences were found:\n\n" + errorMessage);
    }
};

/**
 * Creates a JSON file in a given directory with a given file name, used to record test results of individual test cases
 * @param  {object} testCaseObject - A test case JSON object
 * @param  {string} dirPath - The path to the directory where the file will be saved
 * @param  {string} fileName - The name of the file that will be created.
 */
validationLibrary.recordResults = function(testCaseObject, dirPath, fileName) {
    if (!(fs.existsSync(dirPath))) {
        fs.mkdir(dirPath, function (err) {
            if (err) {
                return console.log(err);
            }
        });
    }
        
    let filePath = dirPath + "/" + fileName + ".json";
    fs.writeFile(filePath, JSON.stringify(testCaseObject, null, '\t'), function(err) {
        if (err) {
            return console.log(err);
        }
    });
    
};

module.exports = validationLibrary;